config/routes.rb
Rails.application.routes.draw do

# 管理者側のルーティング

  # 管理者側ログイン
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions',
  #   passwords:     'admins/passwords'
  # }
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  # 管理者側機能
  namespace :admin do

    get '/' => 'homes#top'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
  end

# 会員側のルーティング

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :products, only: [:show, :index]
    resources :cart_products, only: [:index, :create, :update, :destroy] do
    collection do
    delete 'destroy_all'
    end
    end
    resources :orders, only: [:index, :new, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    get '/orders/:id' => 'orders#show', as: 'order'
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  
  #有効会員かどうか判別 有効ならtrue,無効ならfalse
  def active_for_authentication?
    super && (self.customer_status == true)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:phone_number,:customer_status)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_my_page_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    customers_my_page_path
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        redirect_to new_customer_session_path
      end
    end
  end
 
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="cpntainer">
  <div class="row">
    <div class="col">
      <h4 class="mt-4 mb-4"><span class="bg-light">　<%= @customer.last_name + @customer.first_name %>さんの会員情報編集　</span></h4>
      <%= form_with model:@customer, url: admin_customer_path ,method: :patch, local:true do |f| %>
        <div class="form-group form-inline">
          <%= f.label :"会員ID", class:"col-sm-3 control-label ml-5" %>
          <p class="col-sm-2 ml-4"><%= @customer.id %></p>
        </div>
        <div class="form-group form-inline">
          <%= f.label :"氏名", class:"col-sm-4 control-label" %>
          <%= f.text_field :last_name, autofocus: true, placeholder: "令和", class:"col-sm-2 form-control" %>
          <%= f.text_field :first_name, autofocus: true, placeholder: "道子", class:"col-sm-2 form-control ml-5" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :"フリガナ", class:"col-sm-4 control-label" %>
          <%= f.text_field :last_name_kana, autofocus: true, placeholder: "レイワ", class:"col-sm-2 form-control" %>
          <%= f.text_field :first_name_kana, autofocus: true, placeholder: "ミチコ", class:"col-sm-2 form-control ml-5" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :email, 'メールアドレス', class:"col-sm-4 control-label" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "sample@example.com", class:"col-sm-2 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :postal_code, "郵便番号(ハイフンなし)", class:"col-sm-4 control-label" %>
          <%= f.text_field :postal_code, autofocus: true, placeholder: "0000000", class:"col-sm-2 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :address, "住所", class:"col-sm-4 control-label" %>
          <%= f.text_field :address, autofocus: true, placeholder: "東京都渋谷区代々木神園町0-0", class:"col-sm-5 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :phone_number, "電話番号(ハイフンなし)", class:"col-sm-4 control-label" %>
          <%= f.text_field :phone_number, autofocus: true, placeholder: "00000000000", class:"col-sm-2 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :customer_status, "会員ステータス", class:"col-sm-4 control-label" %>
          <%= f.radio_button :customer_status, TRUE, checked: true %>
          <h5 class="mt-2 ml-1">有効</h5>
          <%= f.radio_button :customer_status, FALSE, class:"ml-4" %>
          <h5 class="mt-2 ml-1">退会</h5>
        </div>
        <div class="text-center">
          <%= f.submit "変更を保存", class:"col-sm-2 btn btn-success mt-3" %>
        </div>
     <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class=="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h4 class="mt-4 mb-4"><span class="bg-light">　会員一覧　</span></h4>
      <table class="table table-hover">
        <thead class="table-active">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          <tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to "#{customer.last_name+customer.first_name}", admin_customer_path(customer) %></td>
              <td><%= customer.email %></td>
              <% if customer.customer_status==true %>
                <td><p class="text-success font-weight-bold"><%= customer.customer_status ? '有効' : '退会' %></p></td>
              <% else %>
                <td><p class="text-black-50"><%= customer.customer_status ? '有効' : '退会' %></p></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p class="mt-4"><%= paginate @customers %></p>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="cpntainer">
  <div class="row">
    <div class="col">
      <h4 class="mt-4 mb-4"><span class="bg-light">　<%= @customer.last_name + @customer.first_name %>さんの会員詳細　</span></h4>
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name %>&nbsp;&nbsp;<%= @customer.first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.last_name_kana %>&nbsp;&nbsp;<%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <% if @customer.customer_status==true %>
            <td><p class="text-success font-weight-bold"><%= @customer.customer_status ? '有効' : '退会' %></p></td>
          <% else %>
            <td><p class="text-black-50"><%= @customer.customer_status ? '有効' : '退会' %></p></td>
          <% end %>
        </tr>
      </table>
      <div class="text-center">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class:"col-sm-2 btn btn-success mt-3" %>
          <%= link_to "注文履歴一覧を見る", admin_path(@customer), class:"col-sm-2 btn btn-primary mt-3 ml-5"%>
        </div>
    </div>
  </div>
</div>