config/routes.rb
Rails.application.routes.draw do

# 管理者側のルーティング

  # 管理者側ログイン
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions',
  #   passwords:     'admins/passwords'
  # }
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  # 管理者側機能
  namespace :admin do

    get '/' => 'homes#top'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
  end

# 会員側のルーティング

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :products, only: [:show, :index]
    resources :cart_products, only: [:index, :create, :update, :destroy] do
    collection do
    delete 'destroy_all'
    end
    end
    resources :orders, only: [:index, :new, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    get '/orders/:id' => 'orders#show', as: 'order'
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   validates :customer_id, presence: true
   validates :postal_code, presence: true
   validates :address, presence: true
   validates :address_name, presence: true
 
  belongs_to :customer

  def full_address
    "〒" + self.postal_code + " " + self.address + " " + self.address_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  validates :customer_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true

  belongs_to :customer
  belongs_to :product

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  
  #有効会員かどうか判別 有効ならtrue,無効ならfalse
  def active_for_authentication?
    super && (self.customer_status == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true

  has_many :products
  
  validates :genre_name, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  validates :customer_id, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
  validates :payment_method, presence: true
  validates :total_price, presence: true
  validates :postage, presence: true
  validates :order_status, presence: true

  belongs_to :customer
  has_many :order_products, dependent: :destroy


  enum payment_method: { credit: 0, bank: 1}

  enum order_status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shipped: 4
  }

  def total
    total = 0
    self.order_products.each do |order_product|
      total += order_product.sub_total
    end
    total
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  validates :order_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true
  validates :product_status, presence: true
  validates :tax_in_price, presence: true

  belongs_to :product
  belongs_to :order

  enum product_status: {
    not_start: 0,
    waiting: 1,
    making: 2,
    completed: 3
  }

  def sub_total
    quantity * tax_in_price
  end


end

app/models/product.rb
class Product < ApplicationRecord
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :sales_status, presence: true

  belongs_to :genre

  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  def tax_included_price
    self.price * 1.1
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top

    if params[:format].present?
      @orders = Order.where(customer_id: params[:format]).page(params[:page]).per(10)
    else
      @orders = Order.all.page(params[:page]).per(10)
    end
    
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show

    @order = Order.find(params[:id])
    @billing = @order.total + @order.postage

  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)

  if order.order_status == "paid_up"

    order.order_products.each do |order_product|

      order_product.update(product_status: "waiting")

    end

    redirect_to admin_order_path(order.id)
  else
    redirect_to admin_order_path(order.id)
  end

  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

  def order_product_params
  params.require(:order_product).permit(:product_status)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

    def after_sign_in_path_for(resource)
      case resource
      when Customer
        root_path(resource)
      when Admin
        admin_path
      end
    end



    def after_sign_out_path_for(resource)
      if resource == :customer
        root_path
      elsif resource == :admin
        new_admin_session_path
      else
        root_path
      end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [
            :email,
            :last_name,
            :first_name,
            :last_name_kana,
            :first_name_kana,
            :postal_code,
            :address,
            :phone_number
            ])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/orders/show.html.erb
<div class="col-md-10 mt-4 ml-">
  <h4 class="mt-4 mb-4"><span class="bg-light">　注文履歴詳細　</span></h4>

　<div class="col-md-5">
  <div class="row">
  <table class="table table-borderless">
    <tr>
      <th scope="row">購入者</th>
      <td>
        <%= link_to admin_customer_path(@order.customer.id) do %>
          <%= @order.customer.last_name %> <%= @order.customer.first_name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">注文日</th>
      <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th scope="row">配送先</th>
      <td>
        〒<%= @order.shipping_postal_code %> <%= @order.shipping_address %><br />
        <%= @order.shipping_name %>
      </td>
    </tr>
    <tr>
      <th scope="row">支払方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <th scope="row">注文ステータス</th>
      <td>
        <%= form_with model: @order, url: admin_order_path(@order), local:true, class: "form-row" do |f| %>
          <%= f.select :order_status, Order.order_statuses_i18n.invert %>
          <%= f.submit " 更新 ", class: 'btn btn-success' %>
        <% end %>
      </td>
    </tr>
  </table>
  </div>
</div>
</div>

<div class="row">
  <div class="col-md-6 mt-4">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">商品名</th>
          <th scope="col">単価(税込)</th>
          <th scope="col">数量</th>
          <th scope="col">小計</th>
          <th scope="col">製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_products.each do |order_product| %>
        <tr>
          <td><%= order_product.product.name %></td>
          <td><%= order_product.tax_in_price.to_s(:delimited, delimiter: ',') %></td>
          <td><%= order_product.quantity %></td>
          <td><%= order_product.sub_total.to_s(:delimited, delimiter: ',') %></td>
          <td>
            <%= form_with model: order_product, url: admin_order_product_path(order_product), method: :patch, local:true, class: "form-row" do |f| %>
              <%= f.select :product_status, OrderProduct.product_statuses_i18n.invert %>
              <%= f.submit "更新", class: 'btn btn-success' %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-6 mt-4">
      <table class="total-box">
        <tr>
          <th>商品合計</th>
          <td><%= @order.total.to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage.to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @billing.to_s(:delimited, delimiter: ',') %></td>
        </tr>
      </table>
    </div>
  </div>
</div>