config/routes.rb
Rails.application.routes.draw do

# 管理者側のルーティング

  # 管理者側ログイン
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions',
  #   passwords:     'admins/passwords'
  # }
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  # 管理者側機能
  namespace :admin do

    get '/' => 'homes#top'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
  end

# 会員側のルーティング

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :products, only: [:show, :index]
    resources :cart_products, only: [:index, :create, :update, :destroy] do
    collection do
    delete 'destroy_all'
    end
    end
    resources :orders, only: [:index, :new, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    get '/orders/:id' => 'orders#show', as: 'order'
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   validates :customer_id, presence: true
   validates :postal_code, presence: true
   validates :address, presence: true
   validates :address_name, presence: true
 
  belongs_to :customer

  def full_address
    "〒" + self.postal_code + " " + self.address + " " + self.address_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  validates :customer_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true

  belongs_to :customer
  belongs_to :product

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  
  #有効会員かどうか判別 有効ならtrue,無効ならfalse
  def active_for_authentication?
    super && (self.customer_status == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true

  has_many :products
  
  validates :genre_name, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  validates :customer_id, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
  validates :payment_method, presence: true
  validates :total_price, presence: true
  validates :postage, presence: true
  validates :order_status, presence: true

  belongs_to :customer
  has_many :order_products, dependent: :destroy


  enum payment_method: { credit: 0, bank: 1}

  enum order_status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shipped: 4
  }

  def total
    total = 0
    self.order_products.each do |order_product|
      total += order_product.sub_total
    end
    total
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  validates :order_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true
  validates :product_status, presence: true
  validates :tax_in_price, presence: true

  belongs_to :product
  belongs_to :order

  enum product_status: {
    not_start: 0,
    waiting: 1,
    making: 2,
    completed: 3
  }

  def sub_total
    quantity * tax_in_price
  end


end

app/models/product.rb
class Product < ApplicationRecord
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :sales_status, presence: true

  belongs_to :genre

  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  def tax_included_price
    self.price * 1.1
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top

    if params[:format].present?
      @orders = Order.where(customer_id: params[:format]).page(params[:page]).per(10)
    else
      @orders = Order.all.page(params[:page]).per(10)
    end
    
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    product = Product.new(product_params)
    if product.save
      redirect_to admin_product_path(product.id)
    else
      @product = Product.new
      @genres = Genre.all
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      redirect_to admin_product_path(product.id)
    else
      @product = Product.find(params[:id])
      @genres = Genre.all
      render :edit
    end
  end


 private
  def product_params
    params.require(:product).permit(:genre_id, :name, :introduction, :price, :image, :sales_status )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

    def after_sign_in_path_for(resource)
      case resource
      when Customer
        root_path(resource)
      when Admin
        admin_path
      end
    end



    def after_sign_out_path_for(resource)
      if resource == :customer
        root_path
      elsif resource == :admin
        new_admin_session_path
      else
        root_path
      end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [
            :email,
            :last_name,
            :first_name,
            :last_name_kana,
            :first_name_kana,
            :postal_code,
            :address,
            :phone_number
            ])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
 <div class="container">
  <div class="row">
    <div class="col">
      <h4 class="mt-4 mb-4"><span class="bg-light">　商品新規登録　</span></h4>
      <%= form_with model:@product, url: admin_product_path, local:true do |f| %>
        <div class="form-group form-inline">
          <%= f.label :image, "商品画像", class:"col-sm-3 control-label ml-5" %>
          <p class="col-sm-2 ml-4"><%= f.attachment_field :image %></p>
        </div>
        <div class="form-group form-inline">
          <%= f.label :name, '商品名', class:"col-sm-4 control-label" %>
          <%=  f.text_field :name, autofocus: true, placeholder:"商品名", class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :introduction, "商品説明", class:"col-sm-4 control-label" %>
          <%= f.text_area :introduction, autofocus: true, placeholder:"ここに説明文を記述します", class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :genre_id, "ジャンルID", class:"col-sm-4 control-label" %>
          <%= f.collection_select :genre_id, @genres, :id, :genre_name, class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :price, "税抜き価格", class:"col-sm-4 control-label" %>
          <%=  f.text_field :price, autofocus: true, placeholder:"1000", class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :sales_status, "販売ステータス", class:"col-sm-4 control-label" %>
          <%= f.radio_button :sales_status, TRUE, checked: true %>
          <h5 class="mt-2 ml-1">販売中</h5>
          <%= f.radio_button :sales_status, FALSE, class:"ml-4" %>
          <h5 class="mt-2 ml-1">販売停止中</h5>
        </div>
        <div class="text-center">
          <%= f.submit "変更を保存", class:"col-sm-2 btn btn-success mt-3" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/admin/products/index.html.erb
<div class="container">
    <div class="col-sm-9 mx-auto">

      <div class="admin-index">
        <h4 class="mt-4 mb-4"><span class="bg-light">　商品一覧　</span>
        <%= link_to new_admin_product_path do%>
          <i class="fas fa-plus size"></i>
        <% end %>
        </h4>
      </div>

      <table class="table table-hover">
          <thead class="table-active">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td><%= link_to product.name, admin_product_path(product.id) %></td>
              <td><%= product.price.to_s(:delimited, delimiter: ',') %></td>
              <td><%= product.genre.genre_name %></td>
              <% if product.sales_status==true %>
                <td><p class="text-success font-weight-bold"><%= product.sales_status ? '販売中' : '販売停止' %></p></td>
              <% else %>
                <td><p class="text-black-50"><%= product.sales_status ? '販売中' : '販売停止' %></p></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      <p class="mt-4"><%= paginate @products %></p>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
 <div class="container">
  <div class="row">
    <div class="col">
      <h4 class="mt-4 mb-4"><span class="bg-light">　商品新規登録　</span></h4>
      <%= form_with model:@product, url: admin_products_path, local:true do |f| %>
        <div class="form-group form-inline">
          <%= f.label :image, "商品画像", class:"col-sm-3 control-label ml-5" %>
          <p class="col-sm-2 ml-4"><%= f.attachment_field :image %></p>
        </div>
        <div class="form-group form-inline">
          <%= f.label :name, '商品名', class:"col-sm-4 control-label" %>
          <%=  f.text_field :name, autofocus: true, placeholder:"商品名", class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :introduction, "商品説明", class:"col-sm-4 control-label" %>
          <%= f.text_area :introduction, autofocus: true, placeholder:"ここに説明文を記述します", class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :genre_id, "ジャンルID", class:"col-sm-4 control-label" %>
          <%= f.collection_select :genre_id, @genres, :id, :genre_name, class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :price, "税抜き価格", class:"col-sm-4 control-label" %>
          <%=  f.text_field :price, autofocus: true, placeholder:"1000", class:"col-sm-3 form-control" %>
        </div>
        <div class="form-group form-inline">
          <%= f.label :sales_status, "販売ステータス", class:"col-sm-4 control-label" %>
          <%= f.radio_button :sales_status, TRUE, checked: true %>
          <h5 class="mt-2 ml-1">販売中</h5>
          <%= f.radio_button :sales_status, FALSE, class:"ml-4" %>
          <h5 class="mt-2 ml-1">販売停止中</h5>
        </div>
        <div class="text-center">
          <%= f.submit "新規登録", class:"col-sm-2 btn btn-success mt-3" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/admin/products/show.html.erb
  <div class="row">
    <div class="col-md-9">
      <h4 class="mt-4 mb-4"><span class="bg-light">　商品詳細　</span></h4>
    </div>
  </div>

    <div class="container">
      <div class="row mt-5 ml-5">
        <div class="d-inline">
          <span><%= attachment_image_tag(@product, :image , width:"300px", format: 'png', fallback: "no_image.jpg") %></span>
        </div>
         <table class="table col-lg-5 d-inline">
            <tr class="text-left">
                <th class="d-block">商品名<span class="ml-5"><%= @product.name %></span></th>
                <th class="d-block">商品説明<span class="ml-5"><%= @product.introduction %></span></th>
                <th class="d-block">ジャンル<span class="ml-5"><%= @product.genre.genre_name %></span></td>
                <th class="d-block">税込価格（税抜価格）<span class="ml-5"><%= @product.tax_included_price.to_i.to_s(:delimited, delimiter: ',') %>(<%= @product.price.to_s(:delimited, delimiter: ',') %>)</span></th>
                <th class="d-block">販売ステータス
                  <span class="ml-5">
                  <% if @product.sales_status==true %>
                    <span class="text-success font-weight-bold ml-5"><%= @product.sales_status ? '販売中' : '販売停止' %></span>
                  <% else %>
                    <span class="text-black-50 ml-5"><%= @product.sales_status ? '販売中' : '販売停止' %></span>
                  <% end %>
                </th>
        </table>
      </div>
    </div>
<div class="text-center">
  <%= link_to "編集する", edit_admin_product_path(@product), class: "btn btn-success" %>
</div>