config/routes.rb
Rails.application.routes.draw do

# 管理者側のルーティング

  # 管理者側ログイン
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions',
  #   passwords:     'admins/passwords'
  # }
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  # 管理者側機能
  namespace :admin do

    get '/' => 'homes#top'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]
  end

# 会員側のルーティング

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :products, only: [:show, :index]
    resources :cart_products, only: [:index, :create, :update, :destroy] do
    collection do
    delete 'destroy_all'
    end
    end
    resources :orders, only: [:index, :new, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    get '/orders/:id' => 'orders#show', as: 'order'
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   validates :customer_id, presence: true
   validates :postal_code, presence: true
   validates :address, presence: true
   validates :address_name, presence: true
 
  belongs_to :customer

  def full_address
    "〒" + self.postal_code + " " + self.address + " " + self.address_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  validates :customer_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true

  belongs_to :customer
  belongs_to :product

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  
  #有効会員かどうか判別 有効ならtrue,無効ならfalse
  def active_for_authentication?
    super && (self.customer_status == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true

  has_many :products
  
  validates :genre_name, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  validates :customer_id, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
  validates :payment_method, presence: true
  validates :total_price, presence: true
  validates :postage, presence: true
  validates :order_status, presence: true

  belongs_to :customer
  has_many :order_products, dependent: :destroy


  enum payment_method: { credit: 0, bank: 1}

  enum order_status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shipped: 4
  }

  def total
    total = 0
    self.order_products.each do |order_product|
      total += order_product.sub_total
    end
    total
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  validates :order_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true
  validates :product_status, presence: true
  validates :tax_in_price, presence: true

  belongs_to :product
  belongs_to :order

  enum product_status: {
    not_start: 0,
    waiting: 1,
    making: 2,
    completed: 3
  }

  def sub_total
    quantity * tax_in_price
  end


end

app/models/product.rb
class Product < ApplicationRecord
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :sales_status, presence: true

  belongs_to :genre

  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  def tax_included_price
    self.price * 1.1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

    def after_sign_in_path_for(resource)
      case resource
      when Customer
        root_path(resource)
      when Admin
        admin_path
      end
    end



    def after_sign_out_path_for(resource)
      if resource == :customer
        root_path
      elsif resource == :admin
        new_admin_session_path
      else
        root_path
      end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [
            :email,
            :last_name,
            :first_name,
            :last_name_kana,
            :first_name_kana,
            :postal_code,
            :address,
            :phone_number
            ])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_header.html.erb
<!--管理側ログイン時ヘッダー-->
<li class="nav-item">
  <%= link_to '商品一覧', admin_products_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %>
</li>

app/views/layouts/_customer_header.html.erb
<!--会員側ログイン時ヘッダー-->
<li class="nav-item">
  <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to "商品一覧", products_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to "カート", cart_products_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-white' %>
</li>

app/views/layouts/_header.html.erb
<!--未ログイン時ヘッダー-->
<li class="nav-item">
  <%= link_to 'About', about_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to '商品一覧',products_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-white'%>
</li>
<li class="nav-item">
  <%= link_to '会員ログイン', new_customer_session_path, class: 'nav-link text-white' %>
</li>
<li class="nav-item">
  <%= link_to '管理者ログイン', new_admin_session_path, class: 'nav-link text-white' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="headline">

        <nav>
          <a href="/"><div class="logo-image"></div></a>

          <% if customer_signed_in? %>
            <div class="welcome">ようこそ、<%= current_customer.last_name %>さん！</div>
          <% end %>

          <ul class="nav-list">
            <!--会員がログインしている時-->
              <% if customer_signed_in? %>
                <%= render 'layouts/customer_header' %>
            <!--管理者がログインしている時-->
              <% elsif admin_signed_in? %>
                <%= render 'layouts/admin_header' %>
            <!--ログインしていないユーザー-->
              <% else %>
                <%= render 'layouts/header' %>
              <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer></footer>

  </body>
</html>